name: react-hono-template

services:
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - 1080:1080
      - 1025:1025
    environment:
      - MAILDEV_OUTGOING_USER=username
      - MAILDEV_OUTGOING_PASS=password
      - MAILDEV_INCOMING_USER=username
      - MAILDEV_INCOMING_PASS=password
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"

  minio_init:
    image: minio/mc
    container_name: minio_init
    depends_on:
      - minio
    environment:
      - MC_USER=admin
      - MC_PASS=password
      - MC_BUCKET=app
    entrypoint: >
      /bin/sh -c "
        until (mc alias set minio http://minio:9000 $$MC_USER $$MC_PASS 2>/dev/null) do echo '...' && sleep 1; done;
        echo 'Creating bucket $$MC_BUCKET';
        mc mb --ignore-existing minio/$$MC_BUCKET;
        exit 0;
      "
